name: fashkart
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  carousel_pro: ^1.0.0
  modal_progress_hud: ^0.1.3
  # The following adds the Cupertino Icons font to your application.
  # Use with the Cupertino Icons class for iOS style icons.
  cupertino_icons: ^0.1.2



dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - images/fash1.jpg
    - images/fash2.jpg
    - images/fash3.jpg
    - images/fash4.jpg
    - images/fash5.jpeg
    - images/fash6.jpg
    - images/cate/jeans.png
    - images/cate/shirts.png
    - images/cate/shoes.png
    - images/cate/suit.png
    - images/cate/tops.png
    - images/cate/watch.png
    - images/products/d.jpeg
    - images/products/f.jpeg
    - images/products/j.jpg
    - images/products/s.jpeg
    - images/products/sh.jpeg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
